export const PERMISSIONS = {
  SUPPORT: 'SUPPORT',

  DOCUMENTS: {
    ERP_SALES: {
      VIEW: 'ERP_SALES_CONSULT',
      CREATE: 'ERP_SALES_CREATE',
      DELETE: 'ERP_SALES_DELETE',
      CHANGE: 'ERP_SALES_CHANGE',
      ACTIVE_OR_INACTIVE: 'ERP_SALES_ACTIVE_OR_INACTIVE',
    },
    ERP_INSTALLMENTS: {
      VIEW: 'ERP_INSTALLMENTS_CONSULT',
      CREATE: 'ERP_INSTALLMENTS_CREATE',
      DELETE: 'ERP_INSTALLMENTS_DELETE',
      CHANGE: 'ERP_INSTALLMENTS_CHANGE',
      ACTIVE_OR_INACTIVE: 'ERP_INSTALLMENTS_ACTIVE_OR_INACTIVE',
    },
    ACQUIRERS_SALES: {
      VIEW: 'ACQUIRERS_SALES_CONSULT',
      CREATE: 'ACQUIRERS_SALES_CREATE',
      DELETE: 'ACQUIRERS_SALES_DELETE',
      CHANGE: 'ACQUIRERS_SALES_CHANGE',
      ACTIVE_OR_INACTIVE: 'ACQUIRERS_SALES_ACTIVE_OR_INACTIVE',
    },
    ACQUIRERS_INSTALLMENTS: {
      VIEW: 'ACQUIRERS_INSTALLMENTS_CONSULT',
      CREATE: 'ACQUIRERS_INSTALLMENTS_CREATE',
      DELETE: 'ACQUIRERS_INSTALLMENTS_DELETE',
      CHANGE: 'ACQUIRERS_INSTALLMENTS_CHANGE',
      ACTIVE_OR_INACTIVE: 'ACQUIRERS_INSTALLMENTS_ACTIVE_OR_INACTIVE',
    },
    ANTICIPATION: {
      VIEW: 'ANTICIPATION_CONSULT',
    },
    SALES_SUMMARY: {
      VIEW: 'SALES_SUMMARY_CONSULT',
    },
    CREDIT_ORDER: {
      VIEW: 'CREDIT_ORDER_CONSULT',
    },
  },

  USERS: {
    VIEW: 'USERS_CONSULT',
    CREATE: 'USERS_CREATE',
    DELETE: 'USERS_DELETE',
    CHANGE: 'USERS_CHANGE',
    ACTIVE_OR_INACTIVE: 'USERS_ACTIVE_OR_INACTIVE',
  },

  COMPANIES: {
    VIEW: 'COMPANIES_CONSULT',
    CREATE: 'COMPANIES_CREATE',
    DELETE: 'COMPANIES_DELETE',
    CHANGE: 'COMPANIES_CHANGE',
    ACTIVE_OR_INACTIVE: 'COMPANIES_ACTIVE_OR_INACTIVE',
  },

  ACQUIRER: {
    VIEW: 'ACQUIRER_CONSULT',
    CREATE: 'ACQUIRER_CREATE',
    DELETE: 'ACQUIRER_DELETE',
    CHANGE: 'ACQUIRER_CHANGE',
    MANAGE_RELATIONS: 'ACQUIRER_MANAGE_RELATIONS',
    ACTIVE_OR_INACTIVE: 'ACQUIRER_ACTIVE_OR_INACTIVE',
  },

  ESTABLISHMENT: {
    VIEW: 'ESTABLISHMENT_CONSULT',
    CREATE: 'ESTABLISHMENT_CREATE',
    DELETE: 'ESTABLISHMENT_DELETE',
    CHANGE: 'ESTABLISHMENT_CHANGE',
    ACTIVE_OR_INACTIVE: 'ESTABLISHMENT_ACTIVE_OR_INACTIVE',
  },

  FLAGS: {
    VIEW: 'FLAGS_CONSULT',
    CREATE: 'FLAGS_CREATE',
    DELETE: 'FLAGS_DELETE',
    CHANGE: 'FLAGS_CHANGE',
    MANAGE_RELATIONS: 'FLAGS_MANAGE_RELATIONS',
    ACTIVE_OR_INACTIVE: 'FLAGS_ACTIVE_OR_INACTIVE',
  },

  CONTRACTS: {
    VIEW: 'CONTRACTS_CONSULT',
    CREATE: 'CONTRACTS_CREATE',
    DELETE: 'CONTRACTS_DELETE',
    CHANGE: 'CONTRACTS_CHANGE',
    ACTIVE_OR_INACTIVE: 'CONTRACTS_ACTIVE_OR_INACTIVE',
  },

  GROUPS: {
    VIEW: 'GROUPS_CONSULT',
    CREATE: 'GROUPS_CREATE',
    DELETE: 'GROUPS_DELETE',
    CHANGE: 'GROUPS_CHANGE',
    MANAGE_USERS: 'GROUPS_MANAGEMENT_USER',
    ACTIVE_OR_INACTIVE: 'GROUPS_ACTIVE_OR_INACTIVE',
    MANAGE_PERMISSIONS: 'GROUPS_MANAGEMENT_PERMISSION',
  },

  HOLIDAYS: {
    VIEW: 'HOLIDAYS_CONSULT',
    CREATE: 'HOLIDAYS_CREATE',
    CHANGE: 'HOLIDAYS_CHANGE',
    DELETE: 'HOLIDAYS_DELETE',
    ACTIVE_OR_INACTIVE: 'HOLIDAYS_ACTIVE_OR_INACTIVE',
  },

  BANKS: {
    VIEW: 'BANK_CONSULT',
    CREATE: 'BANK_CREATE',
    CHANGE: 'BANK_CHANGE',
    ACTIVE_OR_INACTIVE: 'BANK_ACTIVE_OR_INACTIVE',
    BANK_STATEMENT: 'BANK_STATEMENT_CONSULT',
  },

  AUDIT: {
    VIEW: 'AUDIT_MAIL_CONSULT',
  },

  BANKING_DOMICILE: {
    VIEW: 'BANKING_DOMICILE_CONSULT',
    CREATE: 'BANKING_DOMICILE_CREATE',
    CHANGE: 'BANKING_DOMICILE_CHANGE',
    ACTIVE_OR_INACTIVE: 'BANKING_DOMICILE_ACTIVE_OR_INACTIVE',
  },

  NO_FILE_DAY: {
    VIEW: 'NO_FILE_DAY_CONSULT',
    CREATE: 'NO_FILE_DAY_CREATE',
    CHANGE: 'NO_FILE_DAY_CHANGE',
    DELETE: 'NO_FILE_DAY_DELETE',
    ACTIVE_OR_INACTIVE: 'NO_FILE_DAY_ACTIVE_OR_INACTIVE',
  },

  FILE_PROCESSING: {
    READ: 'FILE_PROCESSING_READ',
    PROCESS: 'FILE_PROCESSING_PROCESS',
    REPROCESS: 'FILE_PROCESSING_REPROCESS',
  },

  ADJUSTMENT: {
    TARIFFS_VIEW: 'ADJUSTMENT_TARIFFS_CONSULT',
    CANCELLATION_VIEW: 'ADJUSTMENT_CANCELLATION_CONSULT',
    CHARGEBACK_REQUESTS_VIEW: 'ADJUSTMENT_CHARGEBACK_REQUESTS_CONSULT',
    CHARGEBACK_ANALYSIS_VIEW: 'CHARGEBACK_ANALYSIS_CONSULT',
  },

  CONTRACT_AUDIT: {
    VIEW: 'CONTRACT_AUDIT_CONSULT',
  },

  CONCILIATION: {
    WAITING_VIEW: 'CONCILIATION_WAITING_CONSULT',
    WAITING_PROCESS: 'CONCILIATION_WAITING_PROCESS',
    MANUAL_BANK_RECONCILIATION: 'MANUAL_BANK_RECONCILIATION_PROCESS',
    BANK_ACQUIRER_PROCESS: 'BANK_ACQUIRER_CONCILIATION_PROCESS',
    PIPELINE_VIEW: 'FINANCIAL_RECONCILIATION_PIPELINE_CONSULT',
    PIPELINE_PROCESS: 'FINANCIAL_RECONCILIATION_PIPELINE_PROCESS',
  },

  SETTINGS: {
    SCHEDULER_VIEW: 'SCHEDULER_SETTINGS_CONSULT',
    SCHEDULER_CHANGE: 'SCHEDULER_SETTINGS_PROCESS',
    EMAIL_VIEW: 'EMAIL_SETTINGS_CONSULT',
    EMAIL_CHANGE: 'EMAIL_SETTINGS_PROCESS',
    RECONCILIATION_VIEW: 'RECONCILIATION_SETTINGS_CONSULT',
    RECONCILIATION_CHANGE: 'RECONCILIATION_SETTINGS_PROCESS',
    BACKUP_PROCESS: 'BACKUP_PROCESS',
    EMAIL_LOG_VIEW: 'EMAIL_LOG_CONSULT',
  },

  MANAGEMENT: {
    DASHBOARD_VIEW: 'MANAGEMENT_DASHBOARD_CONSULT',
    DASHBOARD_AUDIT_VIEW: 'DASHBOARD_AUDIT_CONSULT',
  },

  AGENTES: {
    VIEW: 'AGENTES_CONSULT',
    CREATE: 'AGENTES_CREATE',
    CHANGE: 'AGENTES_CHANGE',
    DELETE: 'AGENTES_DELETE',
  },

  PRODUTOS: {
    VIEW: 'PRODUTOS_CONSULT',
    CREATE: 'PRODUTOS_CREATE',
    CHANGE: 'PRODUTOS_CHANGE',
    DELETE: 'PRODUTOS_DELETE',
  },

  MOTIVO_CANCELAMENTO: {
    VIEW: 'MOTIVO_CANCELAMENTO_CONSULT',
    CREATE: 'MOTIVO_CANCELAMENTO_CREATE',
    CHANGE: 'MOTIVO_CANCELAMENTO_CHANGE',
    DELETE: 'MOTIVO_CANCELAMENTO_DELETE',
  },

} as const;

type ValueOf<T> = T[keyof T];
type DeepValueOf<T> = T extends object ? DeepValueOf<ValueOf<T>> : T;

export type Permission = DeepValueOf<typeof PERMISSIONS>;

export const ALL_PERMISSIONS: Permission[] = [
  PERMISSIONS.SUPPORT,
  ...Object.values(PERMISSIONS.USERS),
  ...Object.values(PERMISSIONS.COMPANIES),
  ...Object.values(PERMISSIONS.ACQUIRER),
  ...Object.values(PERMISSIONS.ESTABLISHMENT),
  ...Object.values(PERMISSIONS.FLAGS),
  ...Object.values(PERMISSIONS.CONTRACTS),
  ...Object.values(PERMISSIONS.GROUPS),
  ...Object.values(PERMISSIONS.HOLIDAYS),
  ...Object.values(PERMISSIONS.BANKS),
  ...Object.values(PERMISSIONS.AUDIT),
  ...Object.values(PERMISSIONS.BANKING_DOMICILE),
  ...Object.values(PERMISSIONS.NO_FILE_DAY),
  ...Object.values(PERMISSIONS.FILE_PROCESSING),
  ...Object.values(PERMISSIONS.ADJUSTMENT),
  ...Object.values(PERMISSIONS.CONTRACT_AUDIT),
  ...Object.values(PERMISSIONS.CONCILIATION),
  ...Object.values(PERMISSIONS.SETTINGS),
  ...Object.values(PERMISSIONS.MANAGEMENT),
  ...Object.values(PERMISSIONS.AGENTES),
  ...Object.values(PERMISSIONS.PRODUTOS),
  ...Object.values(PERMISSIONS.MOTIVO_CANCELAMENTO),
];
